# -*- coding: utf-8 -*-
"""Laptop_price_predictor_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FI-UVP8gdq_jpYvmhC2LJxGEx2htgRr8
"""

import streamlit as st

import pickle as pk
import numpy as np

pipe=pk.load(open('pipe.pkl','rb'))
df=pk.load(open('df.pkl','rb'))

st.title('Laptop price Predictor')

df.head(1)

company=st.selectbox('Company',df['Company'].unique())
Type=st.selectbox('Type',df['TypeName'].unique())
Ram=st.selectbox('Ram',df['Ram'].unique())
Weight=st.number_input('Weight')
TouchScreen=st.selectbox('Touchsreen',['Yes','No'])
IPS=st.selectbox('IPS',['Yes','No'])
# screen size
screen_size = st.slider('Scrensize in inches', 10.0, 18.0, 13.0)

# resolution
resolution = st.selectbox('Screen Resolution',['1920x1080','1366x768','1600x900','3840x2160',
                                               '3200x1800','2880x1800','2560x1600','2560x1440','2304x1440'])

CPU=st.selectbox('CPU',df['Cpu_Brand'].unique())
Sdd = st.selectbox('SDD(IN GB)',df['SSD_Memory'].unique())
Hdd=st.selectbox('HDD',['Yes','No'])

GPU=st.selectbox('GPU',df['Gpu_Brand'].unique())
os=st.selectbox('OS',df['OpSys_Split'].unique())

if st.button('Predict Price'):
    ppi=None
    if TouchScreen == 'Yes':
        TouchScreen == 1
    else:
        TouchScreen == 0
    if IPS == 'Yes':
        IPS == 1
    else:
        IPS == 0
    if Hdd == 'Yes':
        Hdd == 1
    else:
        Hdd == 0
    X_res=int(resolution.split('x')[0])
    Y_res=int(resolution.split('x')[1])
    ppi = (((X_res**2) + (Y_res**2))**0.5 / screen_size)
    query=np.array([company,Type,Ram,os,Weight,TouchScreen,IPS,ppi,CPU,Sdd,Hdd,GPU])
    query=query.reshape(1,12)
    st.title("The predicted price of this configuration is " + str(int(np.exp(pipe.predict(query)[0]))))



# prompt: write a program to run streamlit app

